name: Releases

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --frozen-lockfile
      - name: Build
        run: npm run build
      - name: Bundle Files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r vext.zip dist
      - name: Upload ZIP
        uses: actions/upload-artifact@v2
        with:
          name: vext.zip
      - name: Download ZIP
        uses: actions/download-artifact@v2
        with:
          name: vext.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: vext.zip